var mainBoardId,mediaCount,threadReadCountYn,mainType="type2",threadsPageSize=threadsPageSize||dataPerPage,$wrap=$("#wrap");
function mainCommunityCheck(){$.ajax({type:"GET",url:"/api/v1/community/"+_alias+apiParam+"&countryCode="+_countryCode,dataType:"json",contentType:"application/json",async:!1,cache:!1,success:function(a)
{if(_communityId=a.communityId,_lang=a.languageCode,communityTitle=a.userTitle,bgColor=a.communityHome.communityInfo.bgColor,keyColor=a.communityHome.communityInfo.communityColor,isSetAlias=setAlias&&_alias===setAlias,isKMDF="uitestxptmxmxptmxm"===_alias||"dnfmtest"===_alias,threadReadCountYn=a.adminReadCountYn,grade(),$(".game-title").html('<a href="main"><img src="'+a.communityHome.communityInfo.iconImageUrl+'" alt="" class="logo"><h1>'+communityTitle+"</h1></a>"),$(".default-bg .bg-left").attr("src",a.communityHome.communityInfo.bgImageUrl1),$(".default-bg .bg-right").attr("src",a.communityHome.communityInfo.bgImageUrl2),renderMenu(a),renderMainBanners(a),renderSubBanners(a),boards(a),"type2"===mainType){
	var e=a.communityHome.boardInfo;
	mainBoardId=e.boardId||"",_boardType=e.boardType,mediaCount=e.mediaBoardSettingCount,"MEDIA"===_boardType&&(threadsPageSize=mediaCount),a.communityHome.webMediaInfo.linkUrl&&$(".section-top").append('<div class="iframe-wrap">'+a.communityHome.webMediaInfo.linkUrl+"</div>");
var t="",n=a.communityHome.webEventPlace.pcBanners;
if((c=n?n.length:0)>0){t+='<div class="inner">',t+="<ul>";
for(var i=0;i<c;i++){
	var o=n[i];t+="<li>","THREAD"===o.linkType?t+='<a href="board_view?thread='+o.linkValue+'">':"BOARD"===o.linkType?t+='<a href="board_list?board='+o.linkValue+'">':"WEB_LINK"===o.linkType&&(t+='<a href="'+o.linkValue+'" target="_blank">'),t+='<img src="'+o.webImageUrl+'" alt="">',"NONE"!==o.linkType&&(t+="</a>"),t+="</li>"}t+="</ul>",t+="</div>",$(".main .section-banner").html(t)}}
else{
	var r="",s=a.boards.length;r+='<div class="tab-box">',r+='<ul class="swiper-wrapper">';
for(i=0;i<s;i++){
	var l=a.boards[i],d=l.boardType;
	if("ON"===l.release&&"LINK"!==d&&(r+="GROUP"===d?"":'<li class="swiper-slide"><button type="button" data-board-id="'+l.boardId+'" data-board-type="'+l.boardType+'" data-authority="'+l.threadAuthority+'">'+l.title+"</button></li>",l.boards))
	for(var c=l.boards.length,b=0;b<c;b++){
		var p=l.boards[b],u=p.boardType;"ON"===p.release&&"LINK"!==u&&(r+='<li class="swiper-slide"><button type="button" data-board-id="'+p.boardId+'" data-authority="'+p.threadAuthority+'">'+p.title+"</button></li>")}}r+="</ul>",r+='<div class="arrow">',r+='<button type="button" class="btn-left">left</button>',r+='<button type="button" class="btn-right">right</button>',r+="</div>",r+="</div>",$(".main .tab-box").html(r),swiperTab=new Swiper(".tab-box",{slidesPerView:"auto",spaceBetween:50,pagination:{el:".swiper-pagination",clickable:!0},navigation:{nextEl:".tab-box .btn-right",prevEl:".tab-box .btn-left"}})}},error:function(a){console.log("e: ",a)}})}
	function renderMainBanners(a){var e="",t=a.communityHome.webPlace.pcBanners.length;e+='<div class="inner">',e+='<ul class="swiper-wrapper">';
	for(var n=0;n<t;n++){
		var i=a.communityHome.webPlace.pcBanners[n];e+='<li class="swiper-slide">',"THREAD"===i.linkType?e+='<a href="board_view?thread='+i.linkValue+'&bannerBoard=1">':"BOARD"===i.linkType?e+='<a href="board_list?board='+i.linkValue+'">':"WEB_LINK"===i.linkType&&(e+='<a href="'+i.linkValue+'" target="_blank">'),e+='<img src="'+i.webImageUrl+'" alt="">',"NONE"!==i.linkType&&(e+="</a>"),e+="</li>"}e+="</ul>",e+='<div class="controller">',e+='<div class="paging"></div>',e+='<div class="arrow">',e+='<button type="button" class="btn-prev">prev</button>',e+='<button type="button" class="btn-next">next</button>',e+="</div>",e+="</div>",e+="</div>",$(".main .main-banner-box").html(e);
		new Swiper(".main-banner-box .inner",{observer:!0,observeParents:!0,slidesPerView:"type2"===mainType?2:1,spaceBetween:"type2"===mainType?10:0,autoplay:{delay:2500,disableOnInteraction:!1},pagination:{el:".main-banner-box .paging",clickable:!0},navigation:{nextEl:".main-banner-box .btn-next",prevEl:".main-banner-box .btn-prev"}})}
		function renderSubBanners(a){
			var e="",t=a.communityHome.webSubPlace.pcBanners.slice(0,3).length;if(t>0){e+='<ul class="banner-'+t+'">';
		for(var n=0;n<t;n++){
			var i=a.communityHome.webSubPlace.pcBanners[n];e+="<li>","THREAD"===i.linkType?e+='<a href="board_view?thread='+i.linkValue+'">':"BOARD"===i.linkType?e+='<a href="board_list?board='+i.linkValue+'">':"WEB_LINK"===i.linkType&&(e+='<a href="'+i.linkValue+'" target="_blank">'),e+='<img src="'+i.webImageUrl+'" alt="">',"NONE"!==i.linkType&&(e+="</a>"),e+="</li>"}e+="</ul>",$(".sub-banner-box").html(e)}}
			function mainStickyThreadList(){$.ajax({type:"GET",url:"/api/v1/community/"+_communityId+"/stickyThreads"+apiParam+"&pageSize=20",dataType:"json",contentType:"application/json",async:!1,cache:!1,success:function(a){var e="",t=$(".section-top .sticky-box"),n=a.stickyThreads.length,i="type2"===mainType?5:4;if("type2"===mainType&&(e+='<h2 class="message177"></h2>'),e+='<div class="inner">',e+='<div class="swiper-wrapper">',0===n)e+='<p class="result-none">'+message[101]+"</p>";else for(var o=0;o<n;o++){e+="type2"===mainType?'<ul class="swiper-slide type-list">':'<ul class="swiper-slide">';
			for(var r=0;r<i;r++){
				if(o<n){
					var s=a.stickyThreads[o];
					if("type2"===mainType){t=$(".section-bot .sticky-box");
					var l=s.videoCount}
					var d=flattenBoards.filter((function(a){return a.boardId===s.boardId}))[0],c="",b="",p="FORUM"===d.boardType&&s.isAdopt?'class="pick"':"",u=userGradeFunc(s.user),m=u?'<i class="grade-icon" style="background-image:url('+u.iconUrl+');"></i>':"",y=s.user.isAdmin;d.isHeadline&&"0"!==s.headlineId&&(b=(c=d.boardHeadlines.filter((function(a){return a.headlineId===s.headlineId}))[0])&&'<span class="headline">['+c.title+"]</span> "||""),_boardTitle=$('.menu li[data-board-id="'+s.boardId+'"] > a .tit').text(),e+="<li>",e+='<a href="board_view?board='+s.boardId+"&thread="+s.threadId+'&stickyBoard=1">',e+="<h3>",e+='<span class="key-color">['+_boardTitle+"]</span> "+b+"<span "+p+">"+s.title+"</span>",daysAgo(s.createDate)&&(e+='<span class="icon-new"></span>'),e+="</h3>","type2"===mainType&&-1===s.thumbnailImageUrl.indexOf(defaultThumbnail)&&(e+='<div class="list-thumb">',e+='<img src="'+s.thumbnailImageUrl+'" alt="">',l>0&&(e+='<span class="icon-play"></span>'),e+="</div>"),e+="</a>",e+='<dl class="article-info">',e+='<dt class="blind">writer</dt>',!1===s.user.isAdmin?e+='<dd class="writer"><a href="profile?u='+s.user.userId+'">'+m+s.user.nickname+"</a></dd>":e+='<dd class="writer">'+m+s.user.nickname+"</dd>",e+='<dt class="blind">etc</dt>',e+="<dd>",e+='<span class="date">'+dateFunc(s.createDate)+"</span>",isSetAlias&&"ADMIN"===d.threadAuthority||(y?"Y"===threadReadCountYn&&(e+='<span class="count-read">'+s.readCount+"</span>"):e+='<span class="count-read">'+s.readCount+"</span>"),e+='<span class="count-likes">'+s.likeCount+"</span>",e+='<span class="count-comment">'+s.commentCount+"</span>",e+="</dd>",e+="</dl>",e+="</li>"}r!=i-1&&o++}e+="</ul>"}e+="</div>",e+='<div class="controller">',e+='<div class="arrow">',e+='<button type="button" class="btn-prev">prev</button>',e+='<button type="button" class="btn-next">next</button>',e+="</div>",e+='<div class="paging"></div>',e+="</div>",e+="</div>",t.html(e);
					new Swiper(t.find(".inner"),{observer:!0,observeParents:!0,pagination:{el:".sticky-box .paging",type:"fraction"},navigation:{nextEl:".sticky-box .btn-next",prevEl:".sticky-box .btn-prev"}})},error:function(a){console.log("e: ",a)}})}
					function mainThreadsList(){
						var a;"type2"===mainType?a="/api/v1/board/"+mainBoardId+"/threads"+apiParam+"&paginationType=PAGING&pageSize="+threadsPageSize+"&pageNo="+_pageNo+"&blockSize="+pageCount+_blockStartKeyParam+"&blockStartNo="+_blockStartNo:(_boardId||(_boardId=$(".tab-box li").eq(0).find("button").attr("data-board-id")),a="ALL"===_boardType?"/api/v1/community/"+_communityId+"/threads"+apiParam+"&paginationType=PAGING&pageSize="+threadsPageSize+"&pageNo="+_pageNo+"&blockSize="+pageCount+_blockStartKeyParam+"&blockStartNo="+_blockStartNo:"/api/v1/board/"+_boardId+"/threads"+apiParam+"&paginationType=PAGING&pageSize="+threadsPageSize+"&pageNo="+_pageNo+"&blockSize="+pageCount+_blockStartKeyParam+"&blockStartNo="+_blockStartNo),$.ajax({type:"GET",url:a,dataType:"json",contentType:"application/json",async:!1,success:function(a){
							var e="",t=a.threads.length,n=a.totalElements;
						if(_blockStartKey=a.blockStartKey,_blockStartKey){_blockStartKeyParam="";
						for(var i=0;i<_blockStartKey.length;i++)_blockStartKeyParam+="&blockStartKey="+String(_blockStartKey[i])}
						if(_blockStartNo=a.blockStartNo||"","type2"===mainType&&(_boardTitle=mainBoardId?$('.menu li[data-board-id="'+mainBoardId+'"] > a .tit').text():message[3],e+="<h2>"+_boardTitle+"</h2>"),0===t)e+='<p class="result-none">'+message[101]+"</p>";
						else{e+='<div class="inner">',"type2"===mainType&&"MEDIA"===_boardType?e+='<ul class="type-media">':e+='<ul class="type-list">';
						for(i=0;i<t;i++){
							var o=a.threads[i],r=o.videoCount,s=flattenBoards.filter((function(a){return a.boardId===o.boardId}))[0],l="",d="",c="FORUM"===s.boardType&&o.isAdopt?'class="pick"':"",b=userGradeFunc(o.user),p=b?'<i class="grade-icon" style="background-image:url('+b.iconUrl+');"></i>':"",u=o.user.isAdmin;
						if(s.isHeadline&&"0"!==o.headlineId&&(d=(l=s.boardHeadlines.filter((function(a){return a.headlineId===o.headlineId}))[0])&&'<span class="headline">['+l.title+"]</span> "||""),_boardTitle=$('.menu li[data-board-id="'+o.boardId+'"] > a .tit').text(),e+="<li>","ALL"===_boardType?e+='<a href="board_view?board='+o.boardId+"&thread="+o.threadId+'&allBoard=1" data-thread="'+o.threadId+'">':e+='<a href="board_view?board='+o.boardId+"&thread="+o.threadId+'" data-thread="'+o.threadId+'">',"type2"===mainType&&"MEDIA"===_boardType){e+='<div class="media-thumb">',e+='<img src="'+o.thumbnailImageUrl+'" alt="">',r>0&&(e+='<span class="icon-play"></span>'),e+="</div>";
						var m=_boardTitle+o.title,y="";
						if(m.length>46)y=(m.substr(0,44)+"...").replace(_boardTitle,"");
						else y=o.title;e+="<h3>",e+='<span class="key-color">['+_boardTitle+"]</span> "+d+"<span "+c+">"+y+"</span>",daysAgo(o.createDate)&&(e+='<span class="icon-new"></span>'),e+="</h3>"}
						else e+="<h3>",e+='<span class="key-color">['+_boardTitle+"]</span> "+d+"<span "+c+">"+o.title+"</span>",daysAgo(o.createDate)&&(e+='<span class="icon-new"></span>'),e+="</h3>",-1===o.thumbnailImageUrl.indexOf(defaultThumbnail)&&(e+='<div class="list-thumb">',e+='<img src="'+o.thumbnailImageUrl+'" alt="">',r>0&&(e+='<span class="icon-play"></span>'),e+="</div>");e+="</a>",e+='<dl class="article-info">',e+='<dt class="blind">writer</dt>',!1===o.user.isAdmin?e+='<dd class="writer"><a href="profile?u='+o.user.userId+'">'+p+o.user.nickname+"</a></dd>":e+='<dd class="writer">'+p+o.user.nickname+"</dd>",e+='<dt class="blind">etc</dt>',e+="<dd>",e+='<span class="date">'+dateFunc(o.createDate)+"</span>",isSetAlias&&"ADMIN"===s.threadAuthority||(u?"Y"===threadReadCountYn&&(e+='<span class="count-read">'+o.readCount+"</span>"):e+='<span class="count-read">'+o.readCount+"</span>"),e+='<span class="count-likes">'+o.likeCount+"</span>",e+='<span class="count-comment">'+o.commentCount+"</span>",e+="</dd>",e+="</dl>",e+="</li>"}e+="</ul>",mainType&&"type1"!==mainType||(e+='<div class="list-paging"></div>'),e+="</div>"}$(".list-box").html(e),paging(n,dataPerPage,pageCount,_pageNo)},error:function(a){console.log("e: ",a)}})}$((function(){$wrap.addClass("main-"+mainType),"type1"!==mainType&&mainType||(getCookieValue=getPageCookie("pageCookie"),getCookieValue?(getCookieValue=JSON.parse(getCookieValue),_pageNo=getCookieValue._pageNo,_blockStartKeyParam=getCookieValue._blockStartKeyParam,_blockStartNo=getCookieValue._blockStartNo,_boardId=getCookieValue._boardId,_boardType=getCookieValue._boardType):(_pageNo=1,_blockStartKeyParam="",_blockStartNo="",_boardId="",_boardType="")),mainStickyThreadList(),mainThreadsList(),$(".main .tab-box").on("click","li button",(function(){$(".tab-box li button").removeClass("key-color"),$(this).addClass("key-color"),_boardId=$(this).attr("data-board-id"),_boardType=$(this).attr("data-board-type"),_authority=$(this).attr("data-authority"),_blockStartKeyParam="",_pageNo=1,mainThreadsList(),setCookieValue={_pageNo:_pageNo,_blockStartKeyParam:_blockStartKeyParam,_blockStartNo:_blockStartNo,_boardId:_boardId,_boardType:_boardType},setPageCookie("pageCookie",JSON.stringify(setCookieValue))})),$(".main .tab-box li button").each((function(a,e){$(e).attr("data-board-id")===_boardId&&($(".tab-box li button").removeClass("key-color"),$(e).addClass("key-color"),swiperTab.slideTo(a))})),$(".main").on("click",".list-paging",(function(){mainThreadsList()}))})),mainCommunityCheck();